#![allow(dead_code)]
use bevy::prelude::*;
use crate::types::Owner;

// Re-export FactionEnum so that `use crate::game::types::*` still provides it
pub use crate::types::FactionEnum;

/// Component storing faction affiliation for units/buildings
#[derive(Component, Clone, Copy, Debug)]
pub struct FactionMember {
    pub faction: FactionEnum,
    pub player_id: u8,
}

impl FactionMember {
    pub fn new(faction: FactionEnum, player_id: u8) -> Self {
        Self { faction, player_id }
    }

    pub fn color(&self) -> Color {
        self.faction.color()
    }

    pub fn to_owner(&self) -> Owner {
        Owner::player(self.player_id)
    }
}

/// Player entity component — represents a player in the game
#[derive(Component, Clone, Debug)]
pub struct Player {
    pub name: String,
    pub faction: FactionEnum,
    pub player_number: u8,
}

impl Player {
    pub fn new(name: &str, faction: FactionEnum, player_number: u8) -> Self {
        Self {
            name: name.to_string(),
            faction,
            player_number,
        }
    }
}

/// Placeholder component for faction HUD display configuration.
/// Attached to Faction entities to define how their HUD is rendered.
#[derive(Component, Clone, Debug)]
pub struct DisplayHud {
    pub faction: FactionEnum,
}

impl DisplayHud {
    pub fn new(faction: FactionEnum) -> Self {
        Self { faction }
    }
}

/// Placeholder component for player HUD display info.
/// Attached to Player entities to define how their HUD info is rendered.
#[derive(Component, Clone, Debug)]
pub struct DisplayHudInfo {
    pub faction: FactionEnum,
}

impl DisplayHudInfo {
    pub fn new(faction: FactionEnum) -> Self {
        Self { faction }
    }
}

// === Unit Cap Constants ===

/// GDO fixed unit control cap
pub const GDO_UNIT_CONTROL_CAP: u32 = 200;
/// Syndicate maximum tunnel space (hard cap)
pub const SYNDICATE_MAX_TUNNEL_SPACE: u32 = 200;
/// Colonists maximum beacon capacity (hard cap)
pub const COLONISTS_MAX_BEACON_CAPACITY: u32 = 200;
// Cults has no hard cap — army size bounded only by territorial control

/// GDO-specific player resources
#[derive(Component, Clone, Debug)]
pub struct GdoPlayerResources {
    /// Stockpile: gathered crystal amount
    pub space_crystals: i32,
    /// Stockpile: gathered supply amount
    pub supplies: i32,
    /// Capacity: total power generated by power plants
    pub power_generated: i32,
    /// Capacity: total power consumed by buildings
    pub power_consumed: i32,
    /// Capacity (used): number of unit control slots currently in use
    pub unit_control_used: u32,
    /// Capacity (available): fixed at 200
    pub unit_control_cap: u32,
    /// Whether the player owns at least one Power Plant (tech prerequisite)
    pub has_power_plant: bool,
}

impl Default for GdoPlayerResources {
    fn default() -> Self {
        Self {
            space_crystals: 500,
            supplies: 100,
            power_generated: 100,
            power_consumed: 0,
            unit_control_used: 0,
            unit_control_cap: GDO_UNIT_CONTROL_CAP,
            has_power_plant: false,
        }
    }
}

impl GdoPlayerResources {
    /// Net power (generated - consumed)
    pub fn current_power(&self) -> i32 {
        self.power_generated - self.power_consumed
    }

    /// Power ratio for proportional slowdown
    /// Returns 1.0 if power is sufficient, or generated/consumed if in deficit
    pub fn power_ratio(&self) -> f32 {
        if self.power_consumed == 0 || self.current_power() >= 0 {
            1.0
        } else {
            self.power_generated as f32 / self.power_consumed as f32
        }
    }

    /// Check if unit control cap allows more units
    pub fn has_unit_control(&self, cost: u32) -> bool {
        self.unit_control_used + cost <= self.unit_control_cap
    }
}

/// Syndicate-specific player resources
#[derive(Component, Clone, Debug)]
pub struct SyndicatePlayerResources {
    /// Stockpile: gathered crystal amount
    pub space_crystals: i32,
    /// Stockpile: gathered supply amount
    pub supplies: i32,
    /// Capacity (available): provided by Tunnels based on upgrade level, max 200
    pub tunnel_space_provided: u32,
    /// Capacity (used): current tunnel space in use
    pub tunnel_space_used: u32,
}

impl Default for SyndicatePlayerResources {
    fn default() -> Self {
        Self {
            space_crystals: 500,
            supplies: 50,
            tunnel_space_provided: 20,
            tunnel_space_used: 0,
        }
    }
}

impl SyndicatePlayerResources {
    /// Check if tunnel space allows more units
    pub fn has_tunnel_space(&self, cost: u32) -> bool {
        self.tunnel_space_used + cost <= self.tunnel_space_provided
    }
}

/// Cults-specific player resources
#[derive(Component, Clone, Debug)]
pub struct CultsPlayerResources {
    /// Stockpile: gathered crystal amount
    pub space_crystals: i32,
    /// Capacity (used): number of unit control slots currently in use
    pub unit_control_used: u32,
    /// Capacity (available): dynamically provided by RecruitmentCenters (no hard cap)
    pub unit_control_available: u32,
}

impl Default for CultsPlayerResources {
    fn default() -> Self {
        Self {
            space_crystals: 500,
            unit_control_used: 0,
            unit_control_available: 0,
        }
    }
}

impl CultsPlayerResources {
    /// Check if unit control has room for more units
    pub fn has_unit_control(&self, cost: u32) -> bool {
        self.unit_control_used + cost <= self.unit_control_available
    }
}

/// Colonists-specific player resources
#[derive(Component, Clone, Debug)]
pub struct ColonistsPlayerResources {
    /// Stockpile: gathered crystal amount
    pub space_crystals: i32,
    /// Stockpile: refined from SpaceCrystals
    pub alloys: u32,
    /// Stockpile: refined from SpaceCrystals
    pub essence: u32,
    /// Stockpile: refined from Alloys + Essence
    pub conduits: u32,
    /// Capacity (available): provided by Beacons, max 200
    pub beacon_capacity_provided: u32,
    /// Capacity (used): current beacon capacity in use
    pub beacon_capacity_used: u32,
}

impl Default for ColonistsPlayerResources {
    fn default() -> Self {
        Self {
            space_crystals: 500,
            alloys: 50,
            essence: 50,
            conduits: 0,
            beacon_capacity_provided: 20,
            beacon_capacity_used: 0,
        }
    }
}

impl ColonistsPlayerResources {
    /// Check if beacon capacity allows more units
    pub fn has_beacon_capacity(&self, cost: u32) -> bool {
        self.beacon_capacity_used + cost <= self.beacon_capacity_provided
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // === GDO Resource Tests ===

    // === Cap Constants Tests ===

    #[test]
    fn cap_constants_values() {
        assert_eq!(GDO_UNIT_CONTROL_CAP, 200);
        assert_eq!(SYNDICATE_MAX_TUNNEL_SPACE, 200);
        assert_eq!(COLONISTS_MAX_BEACON_CAPACITY, 200);
    }

    #[test]
    fn gdo_default_uses_cap_constant() {
        let res = GdoPlayerResources::default();
        assert_eq!(res.unit_control_cap, GDO_UNIT_CONTROL_CAP);
    }

    #[test]
    fn gdo_default_resources() {
        let res = GdoPlayerResources::default();
        assert_eq!(res.space_crystals, 500);
        assert_eq!(res.supplies, 100);
        assert_eq!(res.unit_control_cap, 200, "GDO unit control cap must be fixed at 200");
        assert_eq!(res.unit_control_used, 0);
    }

    #[test]
    fn gdo_unit_control_cap_enforcement() {
        let res = GdoPlayerResources::default();
        assert!(res.has_unit_control(1));
        assert!(res.has_unit_control(200));
        assert!(!res.has_unit_control(201));
    }

    #[test]
    fn gdo_unit_control_with_existing_usage() {
        let mut res = GdoPlayerResources::default();
        res.unit_control_used = 199;
        assert!(res.has_unit_control(1));
        assert!(!res.has_unit_control(2));
    }

    #[test]
    fn gdo_power_net_calculation() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 100;
        res.power_consumed = 60;
        assert_eq!(res.current_power(), 40);
    }

    #[test]
    fn gdo_power_ratio_sufficient() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 100;
        res.power_consumed = 50;
        assert_eq!(res.power_ratio(), 1.0);
    }

    #[test]
    fn gdo_power_ratio_deficit() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 50;
        res.power_consumed = 100;
        assert!((res.power_ratio() - 0.5).abs() < f32::EPSILON);
    }

    #[test]
    fn gdo_stockpile_increment_decrement() {
        let mut res = GdoPlayerResources::default();
        let initial = res.space_crystals;
        res.space_crystals += 100;
        assert_eq!(res.space_crystals, initial + 100);
        res.space_crystals -= 50;
        assert_eq!(res.space_crystals, initial + 50);
    }

    // === Syndicate Resource Tests ===

    #[test]
    fn syndicate_default_resources() {
        let res = SyndicatePlayerResources::default();
        assert_eq!(res.space_crystals, 500);
        assert_eq!(res.supplies, 50);
        assert_eq!(res.tunnel_space_provided, 20);
        assert_eq!(res.tunnel_space_used, 0);
    }

    #[test]
    fn syndicate_tunnel_space_capacity_tracking() {
        let mut res = SyndicatePlayerResources::default();
        res.tunnel_space_used = 15;
        assert!(res.tunnel_space_used <= res.tunnel_space_provided);
        res.tunnel_space_used = 20;
        assert_eq!(res.tunnel_space_used, res.tunnel_space_provided);
    }

    #[test]
    fn syndicate_has_tunnel_space_within_cap() {
        let res = SyndicatePlayerResources::default();
        assert!(res.has_tunnel_space(1));
        assert!(res.has_tunnel_space(20));
        assert!(!res.has_tunnel_space(21));
    }

    #[test]
    fn syndicate_has_tunnel_space_with_existing_usage() {
        let mut res = SyndicatePlayerResources::default();
        res.tunnel_space_used = 18;
        assert!(res.has_tunnel_space(2));
        assert!(!res.has_tunnel_space(3));
    }

    #[test]
    fn syndicate_has_tunnel_space_at_zero_provided() {
        let mut res = SyndicatePlayerResources::default();
        res.tunnel_space_provided = 0;
        assert!(!res.has_tunnel_space(1));
    }

    // === Cults Resource Tests ===

    #[test]
    fn cults_default_resources() {
        let res = CultsPlayerResources::default();
        assert_eq!(res.space_crystals, 500);
        assert_eq!(res.unit_control_used, 0);
        assert_eq!(res.unit_control_available, 0, "Cults unit control starts at 0 (dynamically provided)");
    }

    #[test]
    fn cults_unit_control_no_hard_cap() {
        let mut res = CultsPlayerResources::default();
        // Cults can have arbitrarily high available unit control
        res.unit_control_available = 1000;
        assert!(res.has_unit_control(1000));
        res.unit_control_available = 10000;
        assert!(res.has_unit_control(10000));
    }

    #[test]
    fn cults_unit_control_dynamic_check() {
        let mut res = CultsPlayerResources::default();
        res.unit_control_available = 10;
        res.unit_control_used = 8;
        assert!(res.has_unit_control(2));
        assert!(!res.has_unit_control(3));
    }

    // === Colonists Resource Tests ===

    #[test]
    fn colonists_default_resources() {
        let res = ColonistsPlayerResources::default();
        assert_eq!(res.space_crystals, 500);
        assert_eq!(res.alloys, 50);
        assert_eq!(res.essence, 50);
        assert_eq!(res.conduits, 0);
        assert_eq!(res.beacon_capacity_provided, 20);
        assert_eq!(res.beacon_capacity_used, 0);
    }

    #[test]
    fn colonists_beacon_capacity_tracking() {
        let mut res = ColonistsPlayerResources::default();
        res.beacon_capacity_used = 15;
        assert!(res.beacon_capacity_used <= res.beacon_capacity_provided);
    }

    #[test]
    fn colonists_has_beacon_capacity_within_cap() {
        let res = ColonistsPlayerResources::default();
        assert!(res.has_beacon_capacity(1));
        assert!(res.has_beacon_capacity(20));
        assert!(!res.has_beacon_capacity(21));
    }

    #[test]
    fn colonists_has_beacon_capacity_with_existing_usage() {
        let mut res = ColonistsPlayerResources::default();
        res.beacon_capacity_used = 18;
        assert!(res.has_beacon_capacity(2));
        assert!(!res.has_beacon_capacity(3));
    }

    #[test]
    fn colonists_has_beacon_capacity_at_zero_provided() {
        let mut res = ColonistsPlayerResources::default();
        res.beacon_capacity_provided = 0;
        assert!(!res.has_beacon_capacity(1));
    }

    #[test]
    fn colonists_stockpile_independence() {
        let mut res = ColonistsPlayerResources::default();
        // Each stockpile resource is independently tracked
        res.alloys += 10;
        res.essence += 20;
        res.conduits += 5;
        assert_eq!(res.alloys, 60);
        assert_eq!(res.essence, 70);
        assert_eq!(res.conduits, 5);
    }

    // === Cap Decrement / Over-Cap Tests ===

    #[test]
    fn gdo_saturating_sub_prevents_underflow() {
        let mut res = GdoPlayerResources::default();
        res.unit_control_used = 0;
        // saturating_sub should prevent underflow
        res.unit_control_used = res.unit_control_used.saturating_sub(5);
        assert_eq!(res.unit_control_used, 0);
    }

    #[test]
    fn gdo_over_cap_blocks_new_units() {
        let mut res = GdoPlayerResources::default();
        // Simulate: cap-providing change reduced cap below usage
        res.unit_control_used = 200;
        res.unit_control_cap = 150; // Hypothetical cap reduction
        assert!(!res.has_unit_control(1), "Should block new units when over cap");
    }

    #[test]
    fn syndicate_over_cap_blocks_new_units() {
        let mut res = SyndicatePlayerResources::default();
        res.tunnel_space_used = 20;
        res.tunnel_space_provided = 10; // Tunnel destroyed, capacity dropped
        assert!(!res.has_tunnel_space(1), "Should block new units when over cap");
    }

    #[test]
    fn cults_over_cap_blocks_new_units() {
        let mut res = CultsPlayerResources::default();
        res.unit_control_used = 50;
        res.unit_control_available = 30; // RecruitmentCenter lost
        assert!(!res.has_unit_control(1), "Should block new units when over cap");
    }

    #[test]
    fn colonists_over_cap_blocks_new_units() {
        let mut res = ColonistsPlayerResources::default();
        res.beacon_capacity_used = 20;
        res.beacon_capacity_provided = 10; // Beacon destroyed
        assert!(!res.has_beacon_capacity(1), "Should block new units when over cap");
    }

    #[test]
    fn gdo_unit_death_frees_cap_space() {
        let mut res = GdoPlayerResources::default();
        res.unit_control_used = 200;
        assert!(!res.has_unit_control(1));
        // Simulate unit death: decrement by cost
        let cost: u32 = 3;
        res.unit_control_used = res.unit_control_used.saturating_sub(cost);
        assert_eq!(res.unit_control_used, 197);
        assert!(res.has_unit_control(3));
        assert!(!res.has_unit_control(4));
    }

    // === Power Grid Tests ===

    #[test]
    fn gdo_power_ratio_zero_generators() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 0;
        res.power_consumed = 50;
        assert_eq!(res.power_ratio(), 0.0);
    }

    #[test]
    fn gdo_power_ratio_zero_consumers() {
        let res = GdoPlayerResources::default();
        // power_consumed is 0 by default
        assert_eq!(res.power_ratio(), 1.0);
    }

    #[test]
    fn gdo_power_ratio_exact_balance() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 50;
        res.power_consumed = 50;
        // Net power is 0, which is >= 0, so ratio should be 1.0
        assert_eq!(res.power_ratio(), 1.0);
    }

    #[test]
    fn gdo_power_ratio_severe_deficit() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 10;
        res.power_consumed = 100;
        let ratio = res.power_ratio();
        assert!((ratio - 0.1).abs() < f32::EPSILON, "Expected 0.1, got {}", ratio);
    }

    #[test]
    fn gdo_current_power_negative() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 20;
        res.power_consumed = 50;
        assert_eq!(res.current_power(), -30);
    }

    #[test]
    fn gdo_current_power_positive() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 100;
        res.power_consumed = 30;
        assert_eq!(res.current_power(), 70);
    }

    #[test]
    fn gdo_power_ratio_zero_both() {
        let mut res = GdoPlayerResources::default();
        res.power_generated = 0;
        res.power_consumed = 0;
        // No consumers means no deficit — ratio is 1.0
        assert_eq!(res.power_ratio(), 1.0);
    }

    // === Cross-Faction Tests ===

    #[test]
    fn each_faction_has_space_crystals() {
        // All factions share space_crystals as a stockpile resource
        let gdo = GdoPlayerResources::default();
        let syn = SyndicatePlayerResources::default();
        let cults = CultsPlayerResources::default();
        let col = ColonistsPlayerResources::default();
        assert_eq!(gdo.space_crystals, 500);
        assert_eq!(syn.space_crystals, 500);
        assert_eq!(cults.space_crystals, 500);
        assert_eq!(col.space_crystals, 500);
    }
}
